### ISSUE TITLE
UserStory #1 - NavBar

### ISSUE THREAD

**Issue by ezecodo** [ezecodo/capstone-kolonol#4]
## Value Proposition

As a User i want to see the Navigation Bar, so can i start using the App.

​

## Description
![navbar](https://user-images.githubusercontent.com/123112219/226318005-4ef19d04-3b83-4bc8-817e-9e0000d753a5.png)

A NavBar with 3 buttons - / Language DE-ES/ Bookmarks / Home

## Acceptance Criteria

- [ ] bottom NavBar with 3 buttons.
- [ ]the NavBar should appear in all Pages.

      ​

## Tasks

- [ ] Create the NavBar with these 3 Buttons (Language/Home/Bookmarks).
- [ ]  + 3 pages where the buttons should link the User.
- [ ] add navigation between the 3 pages.
- [ ] add style to the NavBar
- [ ] Style the NavBar with 'styledComponent'
      ​

## Complexity

M
